### ISSUE TITLE
Batch Size

### ISSUE THREAD

**Issue by joaco18** [nyukat/GMIC#2]
Hi, first of all, congratulations for your work!
While reading the code and the paper, I couldn't find which batch size did you use during training. Could you share that information?
Moreover, the code you are shearing here appears to be just an inference version, I would like to fine-tune the model to some images from a private dataset, so if you could share the training version you used it would be very nice. Furthermore, It would be nice if this repo was complete by itself, to make an inference with your own data you have to preprocess (cropping and reshaping) the images separately using 'breast_cancer_classifier' repo's code.
Thank you!

**Comment by seyiqi** [comment]
Hi,

Thanks for checking out our repository:) The minibatch size we used during training and inference is 4 exams which include 16 mammography images in total.

Unfortunately, we did not include the training code in this repository since it's very much infrastructure-dependent. i.e. in order to make the training work, we need to clean and re-organize pretty much our entire codebase, which requires a lot of effort :(
