### ISSUE TITLE
SystemExit: 2 

### ISSUE THREAD

**Issue by SaiXilinx** [nyukat/GMIC#8]
thnx 4 sharing yr helpful code  I installed all dependencies from requirements.txt & also I'm in the project directory when running bash run.sh
usage: ipykernel_launcher.py [-h] --model-path MODEL_PATH --data-path
                             DATA_PATH --image-path IMAGE_PATH
                             --segmentation-path SEGMENTATION_PATH
                             --output-path OUTPUT_PATH
                             [--device-type {gpu,cpu}]
                             [--gpu-number GPU_NUMBER]
                             [--model-index MODEL_INDEX]
                             [--visualization-flag]
ipykernel_launcher.py: error: the following arguments are required: --model-path, --data-path, --image-path, --segmentation-path, --output-path
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

plz help me!

**Comment by seyiqi** [comment]
Hi,
Thanks for running our code.
I notice that your are running ipykernel_launcher.py rather than src/scritps/run_model.py.

Could you try the following:
1. cd /path/to/GMIC, note that you should cd to the project directory rather than src/scritps 
2. export PYTHONPATH=$(pwd):$PYTHONPATH
3. python3 src/scripts/run_model.py --model-path 'models/' --data-path 'sample_data/data.pkl' --image-path 'sample_data/cropped_images' --segmentation-path 'sample_data/segmentation' --output-path 'sample_output' --device-type 'cpu' --gpu-number 0 --model-index 'ensemble' --visualization-flag

Best
